### ISSUE TITLE
Component binding configuration is rewritten by the app manifest commands

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem-cli#98]
When customizing the WIT binding generator in the `cargo.toml` file like this:

```toml
[package.metadata.component.bindings]
derives = ["serde::Serialize", "serde::Deserialize"]
generate_unused_types = true
```

this section is completely removed by `golem app build` whenever it decides to change the cargo file.
